### ISSUE TITLE
vercel deploy got (no binary found: wrapError)

### ISSUE THREAD

**Issue by scyhz3** [steebchen/prisma-client-go#940]
I have a backend project that uses prisma-client-go. It runs fine in my local environment, but when I deploy the project to Vercel, I encounter an issue at client.Prisma.Connect. The feedback I receive from Vercel is as follows:

<img width="722" alt="截屏2023-08-17 17 43 03" src="https://github.com/steebchen/prisma-client-go/assets/56429884/db25e7b9-30a3-4224-b1d5-6dde523be510">

Hope someone can help me, thanks a lot!

**Comment by steebchen** [comment]
Thanks for the report, I also used to try it on Vercel with a similar error but haven't gotten good feedback from Vercel as they are not spending a lot of time on the Go Vercel runtime as it's not very popular.

Can you maybe share more details on how you're deploying to Vercel, are you using the CLI or is it just automatically deploying from GitHub? Are you commiting the db_gen.go file in your repo or not (I'm wondering because the build seems to work fine, but the binary is not there)

**Comment by scyhz3** [comment]
I deployed the project through this tutorial: https://www.youtube.com/watch?v=jsdyAWc_x08 .

**Comment by steebchen** [comment]
Thanks that helps, will take a closer look when I find some time

**Comment by scyhz3** [comment]
Hi steebchen, I try the AWS lambda instand of vercel. However, I got this error: could not read user cache dir: neither $XDG_CACHE_HOME nor $HOME are defined. 

<img width="843" alt="截屏2023-08-21 20 24 13" src="https://github.com/steebchen/prisma-client-go/assets/56429884/b043d348-e9af-460d-b713-261974b8d2ba">

I realized that the .cache file is in my root directory. I didn't push it into my aws server. However, I don't know how to update it into the AWS. I tried to create a directory store the .cache directory in my project and set the environment like XDG_CACHE_HOME=cache/.cache. But it did not work.

<img width="882" alt="截屏2023-08-21 20 39 47" src="https://github.com/steebchen/prisma-client-go/assets/56429884/4fb8c104-94ec-4998-95b8-8065899e21e8">

Do you know how to set the $XDG_CACHE_HOME or $HOME?
Is it possible for me to create a docker image for the project and push it into AWS? Dose the .cache directory can also be packaged into the docker image?

Thank you very much!

**Comment by steebchen** [comment]
I think your best bet is to use a dockerized service like Google Cloud Run or ECS, because any dockerfile will work, even with the Go client.
Regarding the .cache thing above I'm not really sure if that's related to the Go client. I didn't look into lambda/vercel yet, it's probably something which can be fixed in the Go client or with docs but as I said I would have to look into it.

**Comment by scyhz3** [comment]
Got it! Thank you!

**Comment by nettrino** [comment]
@steebchen I got the same error in an AWS lambda and this is a dockerized lambda. prisma-client-go also runs fine locally. On my python lambdas which use a different driver, I had to set `ENV PRISMA_HOME_DIR="/var/tmp"` inside Dockerfile, but this does not do the trick here - _looking into it_

**Comment by nettrino** [comment]
@steebchen It worked, however despite the fact that I had set `PRISMA_GLOBAL_TEMP_DIR` still got a warning
```could not detect user cache dir (falling back to /tmp): neither $XDG_CACHE_HOME nor $HOME are defined```

**Comment by steebchen** [comment]
Thanks so much for checking! Could you do me one more favor please and check if the branch `cache-dir-temp` works (install via `go get github.com/steebchen/prisma-client-go@cache-dir-temp` and re-generate the client)? It will probably log something still, but I just want to check if my new changes will also work on Lambda.

**Comment by steebchen** [comment]
Release via [v0.23.0](https://github.com/steebchen/prisma-client-go/releases/tag/v0.23.0). Closing this for now. Please re-open if any issues still occur.
